version: '3.7'
services:
  #--CLUSTER-SMI ROUTER (has to run on a single machine with specific ports opened (configured in Dockerfile), no GPU required-----------------------------------------------
  cluster-smi-router:
    image: medgift/cluster-smi-docker:latest
    network_mode: "host"
    volumes:
      - <local_config_file_path>:/cluster-smi.yml
    command: ./cluster-smi-router
    restart: always
